### ISSUE TITLE
Background collor

### ISSUE THREAD

**Issue by Simracer2018** [arv187/PREM-Podium-race-E-manager#47]
Hello, where can I possibly for all sides the background [collor] or maybe even a picture change / insert?
Thank you in advance for your help!
greeting

**Comment by avs-code** [comment]
**-To change blackground colour**
In Index.php file, Line 50.
Add the blackground color code:
`background-color: lightblue;`
*_lightblue is a example, you can use others colours._
It should show something like this:
```php
body {font-family: "Lato", sans-serif; background-color: lightblue;}
```
*_note that each commando must be separated by_ `;`

If you want use a image as blackground try this:
`background-image: url("images/2011_FIA_GT1_Silverstone_2.jpg");`
It should show something like this:
```php
body {font-family: "Lato", sans-serif; background-image: url("images/2011_FIA_GT1_Silverstone_2.jpg");}
```
*_note that the url is relative to the installation of PREM_ 

To more info PREM use the W3 css styles:
https://www.w3schools.com/css/css_background.asp

**- To change or insert picture in slider show**
The file is main.php line 47
Here you have  the url to image and their height:
```php
<img src="images/2011_FIA_GT1_Silverstone_2.jpg" style="height:500px">
```
Image title:
`<h3>FIA GT1 at Silverstone in 2011</h3>`
And image description:
`<p><b>By ToNG!? - FIA GT1, CC BY 2.0, https://commons.wikimedia.org/w/index.php?curid=20368769</b></p>`

**P.S:** Show me your website if you want to see how it looks with your changes. 😃

**Comment by Simracer2018** [comment]
Thanks for the quick and good help. Worked !!!
